#!/usr/bin/env bash

set -x

set -eo pipefail

# # Abort if not running in a Linux environment
# if [[ "$(uname -s)" != "Linuxs" ]]; then
#   echo "This script is intended to run on Linux environments only."
#   exit 1
# fi

WPENV_INSTALLPATH="$(realpath --relative-to $(pwd) $(pnpm exec wp-env install-path))"

# # phpunit : install missing yoast/phpunit-polyfills
# # this is neeed to run the tests in the WordPress environment
# # @TODO: dont know why this is not automatically installed by wp-env, investigate into issue and fix it in wp-env
# pnpm wp-env run tests-wordpress composer global require yoast/phpunit-polyfills:"^3.0" -W --dev

# # copy phpunit files from wp-env container to phpunit-wordpress
# WORDPRESS_TEST_CONTAINER=$(docker ps -q --filter "name=tests-wordpress")
# docker cp "$WORDPRESS_TEST_CONTAINER:/home/$USER/.composer/vendor/" "$(pwd)/phpunit/"

# # copy our phpunit config and bootstrap file to the wp-env wordpress test instance instead of mapping them in wp-env.json
# docker cp "$(pwd)/phpunit/phpunit.xml" "$WORDPRESS_TEST_CONTAINER:/var/www/html/"
# docker cp "$(pwd)/phpunit/bootstrap.php" "$WORDPRESS_TEST_CONTAINER:/var/www/html/"

# suppress xdebug log messages when digging into wp-env containers
prefix=$(basename "$(pnpm wp-env install-path)")
# iterate over all wp-env containers and add "xdebug.log_level=0" to php.ini if not already present
for suffix in 'cli-1' 'tests-cli-1' 'tests-wordpress-1' 'wordpress-1' ; do
  cat <<EOF | docker exec --interactive -u root "${prefix}-${suffix}" sh -
    grep -q 'xdebug.log_level=' /usr/local/etc/php/php.ini || \
      echo "xdebug.log_level=0" >> /usr/local/etc/php/php.ini
EOF
done


    # generate launch configuration
    mkdir -p '.vscode'
    cat << EOF > '.vscode/launch.json'
{
  // THIS FILE IS MACHINE GENERATED by .wp-env-afterStart.sh - DO NOT EDIT!
  // If you need to confgure additional launch configurations consider defining them in a vscode *.code-workspace file
  "version": "0.2.0",
  "configurations": [
    {
      "name": "wp-env",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "stopOnEntry": false, // set to true for debugging this launch configuration
      "log": false,         // set to true to get extensive xdebug logs
      "pathMappings": {
        "/var/www/html/wp-content/plugins/ionos-blueprints-light":"\${workspaceFolder}/ionos-blueprints-light",
        "/var/www/html": "\${workspaceFolder}/${WPENV_INSTALLPATH}/WordPress",
        // phpunit test path mappings
        "/wordpress-phpunit/includes": "\${workspaceFolder}/${WPENV_INSTALLPATH}/tests-WordPress-PHPUnit/tests/phpunit/includes",
        "/home/$USER/.composer/vendor": "\${workspaceFolder}/phpunit/vendor",

      }
    }
  ]
}
EOF

# remove dolly demo plugin
rm -f $WPENV_INSTALLPATH/{tests-WordPress,WordPress}/wp-content/plugins/hello.php

for prefix in '' 'tests-' ; do
  # this wp-cli configuration file needs to be created to enable wp-cli to work with the apache mod_rewrite module
  pnpm exec wp-env run ${prefix}cli sh -c 'echo -e "apache_modules:\n  - mod_rewrite" > /var/www/html/wp-cli.yml'

  # The wp rewrite structure command updates the permalink structure. --hard also updates the .htaccess file
  pnpm exec wp-env run ${prefix}cli wp --quiet rewrite structure '/%postname%' --hard

  # The wp rewrite flush command regenerates the rewrite rules for your WordPress site, which includes refreshing the permalinks.
  pnpm exec wp-env run ${prefix}cli wp --quiet rewrite flush

  # Updates an option value for example the value of Simple page is id = 2
  pnpm exec wp-env run ${prefix}cli wp --quiet option update page_on_front 2
  # Update the page as front page by default.
  pnpm exec wp-env run ${prefix}cli wp --quiet option update show_on_front page

  # activate twentytwenty-five theme in all wp-env instances (test and development)
  pnpm exec wp-env run ${prefix}cli wp --quiet theme activate twentytwentyfive

  # activate all installed plugins in all wp-env instances (test and development)
  pnpm exec wp-env run ${prefix}cli wp --quiet plugin activate --all

  # pnpm exec wp-env run ${prefix}cli sh -c 'sudo chmod a+w -R /var/www/html/phpunit.xml' 2>/dev/null || true
  # pnpm exec wp-env run ${prefix}cli sh -c 'sudo chmod a+w -R /var/www/html/bootstrap.php' 2>/dev/null || true
done
