#!/usr/bin/env bash

set -eo pipefail

# # Abort if not running in a Linux environment
# if [[ "$(uname -s)" != "Linuxs" ]]; then
#   echo "This script is intended to run on Linux environments only."
#   exit 1
# fi

readonly WPENV_INSTALLPATH="$(realpath --relative-to $(pwd) $(pnpm exec wp-env install-path))"

# suppress xdebug log messages when digging into wp-env containers
readonly WP_ENV_HASH=$(basename "$(pnpm wp-env install-path)")
# iterate over all wp-env containers and add "xdebug.log_level=0" to php.ini if not already present
for suffix in 'cli-1' 'tests-cli-1' 'tests-wordpress-1' 'wordpress-1' ; do
  cat <<EOF | docker exec --interactive -u root "${WP_ENV_HASH}-${suffix}" sh -
    grep -q 'xdebug.log_level=' /usr/local/etc/php/php.ini || \
      echo "xdebug.log_level=0" >> /usr/local/etc/php/php.ini
EOF
done

# generate launch configuration
mkdir -p '.vscode'
cat << EOF > '.vscode/launch.json'
{
  // THIS FILE IS MACHINE GENERATED by .wp-env-afterStart.sh - DO NOT EDIT!
  // If you need to confgure additional launch configurations consider defining them in a vscode *.code-workspace file
  "version": "0.2.0",
  "configurations": [
    {
      "name": "wp-env",
      "type": "php",
      "request": "launch",
      "port": 9003,
      "stopOnEntry": false, // set to true for debugging this launch configuration
      "log": false,         // set to true to get extensive xdebug logs
      "pathMappings": {
        "/var/www/html/wp-content/plugins/ionos-blueprints-light":"\${workspaceFolder}/ionos-blueprints-light",
        "/var/www/html": "\${workspaceFolder}/${WPENV_INSTALLPATH}/WordPress",
        // phpunit test path mappings
        "/wordpress-phpunit/includes": "\${workspaceFolder}/${WPENV_INSTALLPATH}/tests-WordPress-PHPUnit/tests/phpunit/includes",
        "/home/$USER/.composer/vendor": "\${workspaceFolder}/phpunit/vendor",
      }
    }
  ]
}
EOF

# phpunit : install missing yoast/phpunit-polyfills
# this is neeed to run the tests in the WordPress environment
pnpm wp-env run tests-wordpress composer global require yoast/phpunit-polyfills:"^3.0" -W --dev

# remove dolly demo plugin
rm -f $WPENV_INSTALLPATH/{tests-WordPress,WordPress}/wp-content/plugins/hello.php

start=$(date +%s)
for prefix in '' 'tests-' ; do
  docker exec -i "${WP_ENV_HASH}-${prefix}cli-1" /bin/bash <<EOF
    set -x

    # this wp-cli configuration file needs to be created to enable wp-cli to work with the apache mod_rewrite module
    echo -e "apache_modules:\n  - mod_rewrite" > /var/www/html/wp-cli.yml

    # The wp rewrite structure command updates the permalink structure. --hard also updates the .htaccess file
    wp --quiet --skip-plugins rewrite structure '/%postname%' --hard

    # The wp rewrite flush command regenerates the rewrite rules for your WordPress site, which includes refreshing the permalinks.
    wp --quiet --skip-plugins rewrite flush

    # Updates an option value for example the value of Simple page is id = 2
    wp --quiet --skip-plugins option update page_on_front 2
    
    # Update the page as front page by default.
    wp --quiet --skip-plugins option update show_on_front page
    
    # activate twentytwenty-five theme in all wp-env instances (test and development)
    wp --quiet --skip-plugins theme activate twentytwentyfive
    
    # activate all installed plugins in all wp-env instances (test and development)
    wp --quiet --skip-plugins plugin activate --all

    # Install the localhost2host-docker-internal plugin as an mu-plugin
    wp --quiet --skip-plugins plugin install https://downloads.wordpress.org/plugin/localhost2host-docker-internal.zip
    mv /var/www/html/wp-content/plugins/localhost2host-docker-internal /var/www/html/wp-content/mu-plugins/
EOF
done
# echo elapsed time in seconds splitted by . as thousand separator
printf "⌛ %s seconds elapsed\n" "$(echo $(( $(date +%s) - $start )) | sed ':a;s/\B[0-9]\{3\}\>/.&/;ta')"